### ISSUE TITLE
can't identify 18F26k20

### ISSUE THREAD

**Issue by Nudels** [gphalkes/fpicprog#1]
I think there is maybe a bug:

$ sudo ./fpicprog -verbosity 4 -action identify --family pic18
fpicprog.cc:211: (1) Failed to read a valid device ID

can you help me to fix that?

building worked, with PicKit3 i can programm it.

here are my pins:
FTDI          ICSP
1 - Black  -> 3 - GND
2 - Brown  -> 6 - PGM
3 - Red    -> 2 - VDD
4 - Orange -> 1 - ~MCLR/VPP
5 - Yellow -> 4 - PGD
6 - Green  -> 5 - PGC

**Comment by gphalkes** [comment]
Thanks for trying out fpicprog, and for reporting the issue. Apologies for not answering sooner, I was on vacation. Would you be able to run the command above with --verbosity=10? That will print all the data that was received from the device, and should show if there is any data being received at all.

Most likely there is an issue with the pin configuration. I'm not able to deduce what pins of the FTDI chip are connected to the which pins on the PIC18 as I don't know what device you are attempting to use and hence don't know what the color coding is. Typically the output pins are marked with letter combinations like CTS, DTR, TxD etc. Those would be very helpful to have.

**Comment by Nudels** [comment]
Hi, thanks for answering me.

I am using a FTDI TTL-232R-3V3 cable. I excluded the errors with Vdd (3.3/5V), now i am powering the PIC with 3.3V (not from FTDI) to get the right Vhigh on the pins.

And i checked the LVP bit of the config words, it's enabled.

Here is the pinout for the FTDI adapter i am using:
![screenshot_20180929_190457](https://user-images.githubusercontent.com/1086495/46248522-96067700-c41a-11e8-9a02-cf0a734dcf6c.png)

In the programming sheet (http://ww1.microchip.com/downloads/en/DeviceDoc/41297F.pdf) is not written, that i need the LVP key sequence, so this should not be the problem.

So my new pin connection is:
1 - Black -> 3 - GND
2 - Brown -> 6 - PGM
        3.3V -> 2 - VDD
4 - Orange -> 1 - ~MCLR/VPP
5 - Yellow -> 4 - PGD
6 - Green -> 5 - PGC

Here is the output with verbosity 10:
$ ./fpicprog/src/fpicprog --verbosity 10 -action identify --family pic18
00 01 00 00 10 02 12 00 10 00 10 02 12 02 12 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 02 12 02 12 00 10 02 12 00 10 00 10 02 12 00 10 00 10 00 10 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 08 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 Got bytes 86 01 00 00 00 86 01 00 00 00
00 00 01 00 00 10 02 12 00 10 00 10 02 12 02 12 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 02 12 02 12 00 10 02 12 00 10 00 10 02 12 00 10 00 10 00 10 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 08 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 Got bytes 86 01 00 00 00 86 01 00 00 00
00 00 01 00 00 10 02 12 00 10 00 10 02 12 02 12 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 02 12 02 12 00 10 02 12 00 10 00 10 02 12 00 10 00 10 00 10 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 08 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 Got bytes 86 01 00 00 00 86 01 00 00 00
00 00 01 00 00 10 02 12 00 10 00 10 02 12 02 12 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 02 12 02 12 00 10 02 12 00 10 00 10 02 12 00 10 00 10 00 10 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 08 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 Got bytes 86 01 00 00 00 86 01 00 00 00
00 00 01 00 00 10 02 12 00 10 00 10 02 12 02 12 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 02 12 02 12 00 10 02 12 00 10 00 10 02 12 00 10 00 10 00 10 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 08 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 Got bytes 86 01 00 00 00 86 01 00 00 00
00 00 01 00 00 10 02 12 00 10 00 10 02 12 02 12 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 02 12 02 12 00 10 02 12 00 10 00 10 02 12 00 10 00 10 00 10 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 08 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 Got bytes 86 01 00 00 00 86 01 00 00 00
00 00 01 00 00 10 02 12 00 10 00 10 02 12 02 12 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 02 12 02 12 00 10 02 12 00 10 00 10 02 12 00 10 00 10 00 10 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 08 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 Got bytes 86 01 00 00 00 86 01 00 00 00
00 00 01 00 00 10 02 12 00 10 00 10 02 12 02 12 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 02 12 02 12 00 10 02 12 00 10 00 10 02 12 00 10 00 10 00 10 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 08 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 Got bytes 86 01 00 00 00 86 01 00 00 00
00 00 01 00 00 10 02 12 00 10 00 10 02 12 02 12 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 02 12 02 12 00 10 02 12 00 10 00 10 02 12 00 10 00 10 00 10 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 08 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 Got bytes 86 01 00 00 00 86 01 00 00 00
00 00 01 00 00 10 02 12 00 10 00 10 02 12 02 12 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 02 12 02 12 00 10 02 12 00 10 00 10 02 12 00 10 00 10 00 10 00 10 02 12 00 10 02 12 00 10 00 10 00 10 00 10 08 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 1B 0B 19 09 1B 0B 1B 0B 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 1B 0B 19 09 19 09 1B 0B 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 19 09 Got bytes 86 01 00 00 00 86 01 00 00 00
00 fpicprog.cc:211: (1) Failed to read a valid device ID

**Comment by gphalkes** [comment]
Thanks the information for mentioning the LVP sequence (I hand't thought of that). You might indeed want to try adding --handshake=pgm-first, which should be the version required for your chip. In principle I think it should work without, but it would be useful to at least test that this is not the cause of the issue.

I will need to check the value that is being returned, but I don't think it looks right.

**Comment by Nudels** [comment]
Your device db should be ok, i mean this looks good:

> [18F26K20]
device_id = 2020h
program_memory_size = 10000h

I calculated the id from the bytes i got with verbosity 10, but its not what i should get.

Could it be, that the mapping for the pins is different to mine?
There is some code, which looks like the pinout config, its in https://github.com/gphalkes/fpicprog/blob/master/src/ftdi_sb.cc

> DEFINE_string(ftdi_nMCLR, "TxD", "Pin to use for inverted MCLR.");
DEFINE_string(ftdi_PGC, "DTR", "Pin to use for PGC");
DEFINE_string(ftdi_PGD, "RxD", "Pin to use for PGD");
DEFINE_string(ftdi_PGM, "CTS", "Pin to use for PGM");
DEFINE_int32(ftdi_vendor_id, 0, "Vendor ID of the device to open. Defaults to FTDI vendor ID.");
DEFINE_int32(ftdi_product_id, 0, "Product ID of the device to open. Defaults to FT232 product ID.");
DEFINE_string(ftdi_description, "", "Product description to select which FTDI device to use.");
DEFINE_string(ftdi_serial, "", "Serial number to select which FTDI device to use.");

> FtdiSbDriver::Pin FtdiSbDriver::pins_[] = {
    {"TxD", 0}, {"RxD", 1}, {"RTS", 2}, {"CTS", 3}, {"DTR", 4}, {"DSR", 5}, {"DCD", 6}, {"RI", 7},
};

Is that true?

**Comment by gphalkes** [comment]
That indeed looks like it might be a problem. From the diagram you included, it looks like you need --ftdi_PGC=RTS. The other pins look OK.

**Comment by Nudels** [comment]
Mhhh, i tried with -ftdi_PGC=RTS, but i get the same error after the 10 attemps:

> 00 fpicprog.cc:211: (1) Failed to read a valid device ID

Where you got these information (https://github.com/gphalkes/fpicprog/blob/master/src/util.h):

> enum Pins {
  nMCLR = (1 << 0),
  PGM = (1 << 1),
  PGC = (1 << 2),
  PGD = (1 << 3),
};

Is that true for all FTDIs?

**Comment by Nudels** [comment]
i tried with this:

> ./fpicprog/src/fpicprog -verbosity 10 -action identify -family pic18 -handshake=pgm-first -ftdi_PGC=RTS -ftdi_PGM=RxD -ftdi_PGD=CTS -ftdi_nMCLR=TxD

and changed the connection on the PIC too, but the same problem, no device id :/

**Comment by Nudels** [comment]
OK, i dont know why, but i solved it:

> ./fpicprog/src/fpicprog -verbosity 10 -action identify -family pic18  -ftdi_PGC=RTS -ftdi_PGM=RxD -ftdi_PGD=CTS
00 01 00 00 04 08 0C 00 04 00 04 08 0C 08 0C 00 04 08 0C 00 04 08 0C 00 04 00 04 00 04 00 04 08 0C 08 0C 00 04 08 0C 00 04 00 04 08 0C 00 04 00 04 00 04 00 04 08 0C 00 04 08 0C 00 04 00 04 00 04 00 04 02 03 07 03 07 03 07 03 07 03 0F 0B 0F 0B 0F 0B 0F 0B 0F 0B 0F 0B 07 03 07 03 07 03 0F 0B 0F 0B 0F 0B 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 0F 0B 0F 0B 0F 0B 0F 0B 0F 0B 07 03 0F 0B 0F 0B 0F 0B 07 03 0F 0B 0F 0B 07 03 07 03 07 03 07 03 07 03 0F 0B 0F 0B 0F 0B 0F 0B 0F 0B 0F 0B 0F 0B 0F 0B 07 03 0F 0B 0F 0B 0F 0B 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 0F 0B 0F 0B 0F 0B 07 03 0F 0B 0F 0B 0F 0B 0F 0B 07 03 0F 0B 0F 0B 0F 0B 07 03 0F 0B 0F 0B 07 03 07 03 07 03 07 03 07 03 07 03 0F 0B 0F 0B 0F 0B 0F 0B 0F 0B 0F 0B 0F 0B 07 03 0F 0B 0F 0B 0F 0B 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 0F 0B 0F 0B 07 03 0F 0B 0F 0B 0F 0B 0F 0B 07 03 0F 0B 0F 0B 0F 0B 07 03 0F 0B 0F 0B 07 03 0F 0B 07 03 07 03 0F 0B 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 0F 0B 07 03 07 03 0F 0B 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 07 03 Got bytes 86 01 00 E6 19 86 01 00 00 18
Device 18F26K20, revision 13

Maybe i had a wrong pin connection..

**Comment by gphalkes** [comment]
Cool. Glad to hear you have it working :-)

**Comment by gphalkes** [comment]
Just an FYI: I've made several improvements in the programming speed recently. This means that programming should be about 25 times (!) faster now. I hope this helps :-)

**Comment by ftrentini** [comment]
Good night! I'm having exactly the same problem here. But mine won't start working, at least, not until now!

**Comment by gphalkes** [comment]
The most likely cause is incorrect wiring. Please double check that the pins of the FTDI chip are correctly connected to the pins of your chip. It is unfortunately very easy to get this wrong, especially because the FTDI side isn't always marked very clearly. I'm thinking about adding some options to the program to make this easier, but that probably would need some LEDs.
