### ISSUE TITLE
Not working with PIC18F4450

### ISSUE THREAD

**Issue by dimitry-ishenko** [gphalkes/fpicprog#11]
The programmer ([FT323](https://www.amazon.com/dp/B019I3CAIE)) is detected fine:
```bash
./fpicprog --action=list-programmers
Device:
Vendor ID: 0x0403
Product ID: 0x6001
Description: FT232R USB UART
Serial: AG0KB5RD
```

But, trying to identify the chip I get this:
```bash
./fpicprog --action=identify --family=pic18 --verbosity=9
Got bytes 00 00 00 00 00 00 00 00 00 00
Got bytes 00 00 00 00 00 00 00 00 00 00
Got bytes 00 00 00 00 00 00 00 00 00 00
Got bytes 00 00 00 00 00 00 00 00 00 00
Got bytes 00 00 00 00 00 00 00 00 00 00
Got bytes 00 00 00 00 00 00 00 00 00 00
Got bytes 00 00 00 00 00 00 00 00 00 00
Got bytes 00 00 00 00 00 00 00 00 00 00
Got bytes 00 00 00 00 00 00 00 00 00 00
Got bytes 00 00 00 00 00 00 00 00 00 00
fpicprog.cc:183: (1) Failed to read a valid device ID
```

I am able to connect to the chip and read/write using PICKit 3 and Microchip's [MPLAB IPE](https://www.microchip.com/en-us/development-tools-tools-and-software/embedded-software-center/mplab-integrated-programming-environment) tool.

Any suggestions?

**Comment by gphalkes** [comment]
This typically indicates a problem with the wiring of the chip to the FTDI
chip. Note that the 18F4450 also has a PGM pin, which needs to be wired as
well.

**Comment by dimitry-ishenko** [comment]
@gphalkes you are correct. I was blindsided by the fact that it worked with the PICKit 3 programmer and since it was running off of 5V USB power, I've assumed it was using LVP mode.

I put a scope on it today and it is not the case -- the PICKit is using HVP.
